version: '3.4'

services:
  fastdfs:
    image: season/fastdfs:1.2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  mysql:
    image: mysql:5.7.4
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=ichat
      - MYSQL_USER=ichat
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  ichat:
    image: xx
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - fastdfs
      - mysql
    ports:
      - 3000:3000